# Generated by Django 4.0.10 on 2023-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='-', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
