# Generated by Django 4.0.10 on 2023-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0009_alter_advertisement_image_alter_advertisement_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
