# Generated by Django 4.0.10 on 2023-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0010_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
